### ISSUE TITLE
Fatal server error: .X0-lock

### ISSUE THREAD

**Issue by suharevA** [itsmaniche18/jibri-kubernetes#1]
an error appears when scaling. Until you manually delete the file, it does not work.
Could you build a new container so that this file is deleted at startup

log 
Fatal server error:
(EE) Server is already active for display 0
  If this server is no longer running, remove /tmp/.X0-lock
  and start again.
(EE)

**Comment by itsmaniche18** [comment]
If you have already pulled the image to your local then you can delete and push it on the docker hub so that you can use your deleted image

Thanks
If you didn't understand you can add me on skype --> itsmaniche18

**Comment by suharevA** [comment]
it works like that
