### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DamianoP** [itsmaniche18/jibri-kubernetes#2]
can you explain better how to use your code and connect jibri instances to jitsi instances ? 
A more detailed readme would be very useful

**Comment by itsmaniche18** [comment]
First of all, you have to create a Kubernetes master and nodes 
Used 8 Cores 16 GB RAM from AWS instance type c5.2xlarge as 1 Jibri takes 2 cores is the reason to use four stateful sets.

For this you have to enable sound modules 
To see all the devices,
$ aplay -l
f you couldn't find any card devices, then install alsa module.
$ apt install alsa-utils
To increase the loopback cards,
$ lsmod | grep snd_aloop
$ echo "options snd-aloop enable=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 index=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29" > cat /etc/modprobe.d/alsa-loopback.conf
$ modprobe snd_aloop
Check if the module is loaded
$ lsmod | grep snd_aloop
$ aplay -l


After the sound module is loaded change your values in configMap.yaml {meet.example.com to your-domain-name }
Change the file accordingly.
  
 Apply all the yml files to deploy the multiple JIbris.
 
If there is any confusion you can add me on skype --> itsmaniche18
